<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PlanetaryMock</RootNamespace>
    <AssemblyName>PlanetaryMock</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Assets/scripts/game/BasicCollision.cs" />
    <Compile Include="Assets/scripts/game/CharacterSettings.cs" />
    <Compile Include="Assets/scripts/game/SaveData.cs" />
    <Compile Include="Assets/scripts/game/SaveManager.cs" />
    <Compile Include="Assets/scripts/game/JsonHelper.cs" />
    <Compile Include="Assets/scripts/game/LevelBase.cs" />
    <Compile Include="Assets/scripts/game/SceneSettings.cs" />
    <Compile Include="Assets/scripts/items/ItemException.cs" />
    <Compile Include="Assets/scripts/items/ItemInventory.cs" />
    <Compile Include="Assets/scripts/items/ItemTypes.cs" />
    <Compile Include="Assets/scripts/items/KnownItemsInventory.cs" />
    <Compile Include="Assets/scripts/items/PlayerInventory.cs" />
    <Compile Include="Assets/scripts/solarbits/PlayerWallet.cs" />
    <Compile Include="Assets/scripts/solarbits/SolarbitsWallet.cs" />
    <Compile Include="Assets/scripts/solaros/ISolarOS.cs" />
    <Compile Include="Assets/scripts/solaros/SolarOSApplication.cs" />
    <Compile Include="Assets/scripts/solaros/SolarOSMenu.cs" />
    <Compile Include="Assets/scripts/solaros/IDialogConsole.cs" />
    <Compile Include="Assets/scripts/solaros/SolarOSNetwork.cs" />
    <Compile Include="Assets/scripts/solaros/SolarOSGIT.cs" />
    <Compile Include="Assets/scripts/solaros/SolarOSSocialMedia.cs" />
    <Compile Include="Assets/scripts/solaros/SolarOSWeb.cs" />
    <Compile Include="Assets/scripts/solaros/SolarOS.cs" />
    <Compile Include="Assets/scripts/solaros/TinyOS.cs" />
    <Compile Include="Assets/scripts/level2/LevelController_2.cs" />
    <Compile Include="Assets/scripts/level2/Level_2_interrogation.cs" />
    <Compile Include="Mocks/UnityEngine.cs" />
    <Compile Include="Mocks/UnityEngineSceneManagement.cs" />
    <Compile Include="Mocks/UnityEngineUI.cs" />
  </ItemGroup>

</Project>
